spring:
  datasource:
    url: jdbc:mysql://localhost:3306/food_delivery_app
    username: root
    password: Stanislava99.
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  application:
    name: api_auth

server:
  port: 8090

eureka:
  client:
    service-url:
      default-zone: ${EUREKA.URI:http://localhost:8761/eureka}
    instance:
      prefer-ip-address: true