server:
  port: 8080

eureka:
  client:
    service-url:
      default-zone: ${EUREKA.URI:http://localhost:8761/eureka}


spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  application:
    name: api-gateway

zuul:
  routes:
    auth-server:
      path: /auth-api/**
      serviceId: auth-service
      strip-prefix: false
    order-server:
      path: /order-api/**
      serviceId: order-service
      strip-prefix: false
    restaurant-server:
      path: /restaurant-api/**
      serviceId: restaurant-service
      strip-prefix: false
  ignored-services: '*'
