server:
  port: 8001
  servlet:
    context-path: /restaurant-api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurantdb?createDatabaseIfNotExist=true
    username: root
    password: Stanislava99.
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: true
  application:
    name: restaurant-service


security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9191/auth-api/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true
    lease-expiration-duration-in-seconds: 1
    lease-renewal-interval-in-seconds: 2