server:
  port: 8001
  servlet:
    context-path: /restaurant-api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/food_delivery_app
    username: root
    password: Stanislava99.
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  application:
    name: restaurant-service

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9191/auth-api/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin
