server:
  port: 8002
  servlet:
    context-path: /order-api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order-service?autoreconnect=true
    username: root
    password: Stanislava99.
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: true
  application:
    name: order-service
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: order-service
    user: "root"
    password: "Stanislava99."
    locations: db-order/migrations
    sql-migration-prefix: V
    sql-migration-separator: __
    baseline-version: 1
    enabled: true

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9191/auth-api/oauth/check_token
    client:
      client-secret: pin
      client-id: mobile

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true
    lease-expiration-duration-in-seconds: 1
    lease-renewal-interval-in-seconds: 2
