server:
  port: 8002

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/food_delivery_app
    username: root
    password: Stanislava99.
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  application:
    name: order-service


